add test

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -32,4 +32,10 @@ jobs:
       # Runs a set of commands using the runners shell
       - name: Run a multi-line script
         run: |
-          return 1
+          set -e
+          last_release=$(git branch --all --list '*release/20*' | sort -r | head -n 1 | cut -c18-)
+          if [ $GITHUB_BASE_REF == last_release ]
+          then
+            echo "ERROR: target branch is old (got \"${GITHUB_BASE_REF}\", expected \"${last_release}\")"; return 1
+          fi
+          return 0
